seleniumGrid = false
gridURL = http://localhost:4444/wd/hub

#Application URL

url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url_local = http://localhost/orangehrm/orangehrm-5.8/web/index.php/auth/login
url_grid = http://host.docker.internal/orangehrm/orangehrm-5.8/web/index.php/auth/login

#Browser Configuration
browser = chrome

#Credentials
username = rootgly
password = F_society01

#ImplicitWait (in seconds)
implicitWait = 10

#ExplicitWait (in seconds)
explicitWait = 30